version: '3.8'

services:
  ncu_ipap_php:
    build: ./php
    environment:
      - DB_HOST=ncu_ipap_db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    env_file:
      - .env  # Archivo adicional de variables
    container_name: ncu_ipap_php
    volumes:
      - ./:/var/www/html
    networks:
      - ncu_ipap_net

  ncu_ipap_db:
    image: mariadb:11
    
    environment:
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
        MYSQL_DATABASE: ${DB_NAME}
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASS}
    container_name: ncu_ipap_db 
    volumes:
      - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ncu_ipap_net

  ncu_ipap_nginx:
    image: nginx:alpine
    container_name: ncu_ipap_nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ncu_ipap_php
    networks:
      - ncu_ipap_net

networks:
  ncu_ipap_net:
    driver: bridge
